name: for miner

on:
  push:
    branches:
      - master
    tags:
    - 'hpool-miner-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
